import Navbar from '@components/navbar/Navbar'
import './globals.css'
import Footer from '@components/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col'>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  )
}
